name: itb_shop
description: iTechBuilders Shop — Android & iOS app (Flutter).
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.5

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_lints: ^4.0.0
